### ISSUE TITLE
xwayland

### ISSUE THREAD

**Issue by MichaelMackus** [michaelforney/swc#49]
Any reason xwayland support was removed? Was this a case of just removing bloat or where things broken? I appreciate the simplicity here but xwayland support would be nice for legacy applications.

**Comment by michaelforney** [comment]
See the commit message of 2011cc74.

I'm no longer using Xwayland, and don't want to continue including code that I haven't even build-tested. If you'd like to re-add it and fix any issue that might come up, that's fine with me.

**Comment by Fixallmyproblems** [comment]
If I'm gonna be honest XWayland support is a big hallmark I miss with swc and of course velox, adding it back in line for line with that old commit message only works with older commits of swc, and swc is a just works out of the box with zero bloat in a suckless fashion type of package, which is why I used it as my main, which I want to use it as my main again still but I don't want to be using old versions without having the ability to update the software, and I don't know how to program in C, maybe in the future I'll get to that but at the same time swc would be perfect instead of wlroots if it had XWayland support added back in if I'm going to be honest with you. XWayland is borderline needed for a TON of applications to be useful especially in the phase of desktop Linux on Wayland, using it without XWayland is suicidal and will not get adapted by anyone trying to make a simple compositor for Wayland, instead they'd go for a much more bloated wlroots, which I don't like any of the wlroots compositors as much as I like the simple velox which is swc based that you made, you don't have to but seriously consider it, it would be a very good move for XWayland to be readded into swc at least for the time being.

**Comment by michaelforney** [comment]
I will think about it, thanks for your comment.

**Comment by bqv** [comment]
I second everything in the above comment

**Comment by michaelforney** [comment]
Since several people have voiced their support for Xwayland, I have merged @bqv's pull request to re-add it.
