### ISSUE TITLE
Cannot connect to wayland server

### ISSUE THREAD

**Issue by Fixallmyproblems** [michaelforney/swc#51]
Disclaimer: I didn't know whether I should have put this in velox or swc until I tried this with other swc based compositors and got the same results, so I'm posting this here.

I am using the latest git commit of swc and I readded Xwayland support because I need Xwayland for backwards compatibility. When I run swc-launch velox it launches flawlessly well along with status_bar however I can't launch anything past that like st for example, and when I exit out of velox I get this: Wayland Dispatch Error: Broken pipe
so I tried doing swc-launch velox && st 
to my avail it launched velox fine per usual but no st (I also tried dmenu and the same results appeared) when I exit out of velox I get the error: Can't open display + Wayland Dispatch Error: Broken pipe . I tried swc-launch && Xwayland and I got more interesting results when I exited out of velox: 
could not connect to wayland server
(EE)
Fatal server error:
(EE) Couldn't add screen
(EE)
then I tried running swc-launch velox && status-bar (I know status-bar is already running but I tried it anyways) and when I exited out I got: status bar: Initializing...FATAL: Failed to connect to display .
Obviously considering that most people aren't running swc or even wayland outside of GNOME, KDE or maybe Sway there wasn't much I could find on this error online so I'm just asking here if there is anything I could do to fix this.

**Comment by michaelforney** [comment]
Can you try running things with `WAYLAND_DEBUG=1`? That will log all wayland protocol events and requests.

Running `swc-launch velox && st` won't do what you want since that won't run st until velox exits. Instead, you can either switch back to the VT you ran `swc-launch velox` from, or run `swc-launch velox & st`, which will run velox in the background, and then start st.

**Comment by michaelforney** [comment]
Actually, that probably won't work either, since st will try to connect to velox before it starts up. You could try `swc-launch velox & sleep 1 && st`.

**Comment by Fixallmyproblems** [comment]
I tried setting WAYLAND_DEBUG=1 and did swc-launch velox & sleep 1 && st and the output as following shows when I exit velox (No actual st working except for the usual velox running just fine) :
[1] 4524
running on /dev/tty1
[swc:libswc/drm.c:150] DEBUG: /dev/dri/card0 is the primary GPU
# find_driver: Trying DRM driver `intel' 
Using config at `/home/gigaboltro/.velox.conf'
[swc:libswc/compositor.c:670] DEBUG: Performing update
[swc:libswc/compositor.c:220] DEBUG: Rendering to target { x: 0, y: 0, w: 1366, h: 768 }
status bar: Initializing...# find_driver: Trying DRM driver `intel'
# find_driver: Trying DRM driver `intel'
# wld_font_open_name: Opening font with name: Terminus:pixelsize=14
# wld_font_open_pattern: Loading font file: /usr/share/fonts/TTF/Vera.ttf
# wld_font_open_pattern: Loading font file: /usr/share/fonts/TTF/LiberationMono-Regular.ttf
done
[swc:libswc/screen.c:180] DEBUG: Updating usable geometry
[swc:libswc/panel.c:176] DEBUG: Original geometry { x1: 0, y1: 0, x2: 1366, y2: 768 }
[swc:libswc/panel.c:194] DEBUG: Usable region { x1: 0, y1: 0, x2: 1366, y2: 768 }
[swc:libswc/compositor.c:670] DEBUG: Performing update
[swc:libswc/compositor.c:220] DEBUG: Rendering to target { x: 0, y: 0, w: 1366, h: 768 }
# wld_font_open_pattern: Loading font file: /usr/share/fonts/TTF/LiberationMono-Italic.ttf
# wld_font_open_pattern: Loading font file: /usr/share/fonts/TTF/LiberationMono-BoldItalic.ttf
# wld_font_open_pattern: Loading font file: /usr/share/fonts/TTF/LiberationMono-Bold.ttf
Segmentation fault
Wayland dispatch error: Broken pipe
^C (I had to force quit cause it wouldn't bring me back to a prompt after I had quit it)
[1] + Done                  \swc-launch velox .
Then when I run just the plan & st I get a simple Wayland dispatch error: Broken pipe. I tried the same with Xwayland and I got an interesting little [swc:libswc/window.c:365] DEBUG: Initializing window, 0x197abc0
and I got Failed to read Wayland events: Broken pipeing to target (and then my screen which I've typed a million times already, you get the gist). Did it with dmenu and finally I got Wayland dispatch error: Broken pipe: again. So basically I have no clue where to go from here

**Comment by michaelforney** [comment]
A few things:

Could you please use code blocks when pasting logs? It's really hard to read your messages. See https://github.github.com/gfm/#fenced-code-blocks.

Are you able to run st from a separate terminal? Otherwise it's hard to see what messages are from st and what messages are from velox.

It doesn't look like `WAYLAND_DEBUG=1` took effect at all, I don't see any wayland protocol logs.

> Segmentation fault

This is the important thing right here. It looks like something (probably st) crashed. I think it is missing some error checking when the server is missing some required globals. What version of st are you using? Now that I think of it, the version in https://github.com/michaelforney/st is using an obsolete xdg-shell protocol, which is no longer supported by the current version of swc. The version of the st patch I'm currently using is at https://github.com/michaelforney/oasis/blob/master/pkg/st/patch/0001-Port-to-wayland-using-wld.patch. I just updated https://github.com/michaelforney/st with the newer version. Please try that.

**Comment by Fixallmyproblems** [comment]
Everything works once you updated st for the new xdg-shell, very much a godsend.
