### ISSUE TITLE
Cant get Velox/Swc to run on my machine!

### ISSUE THREAD

**Issue by jacksmithinsulander** [michaelforney/swc#73]
I'm trying to get velox up and running on my devuan machine, it is starting with your wayland ports of st and dmenu fine, however I cant launch anything, whether from st or from dmenu (tried firefox, netsurf etc)

I see when I swc-launch velox that u get wayland_create_context: DRM  authentication failed, is this the source of my error?

I am on a thinkpad w540, so it is booth using an Nvidia quadro k2100M and intel i7-4800MQ iGPU, maybe thats the problem?

**Comment by michaelforney** [comment]
> I'm trying to get velox up and running on my devuan machine, it is starting with your wayland ports of st and dmenu fine, however I cant launch anything, whether from st or from dmenu (tried firefox, netsurf etc)

Your best bet is to run them with `WAYLAND_DEBUG=1` to see the protocol log, which should indicate why they don't work. If you don't see any output, then they are probably trying to connect via x11. You might have to set some environment variables like `GDK_BACKEND=wayland`.

For firefox, the issue is probably lack of subsurface support in swc. But netsurf should work.

> I see when I swc-launch velox that u get wayland_create_context: DRM  authentication failed, is this the source of my error?

That's not the problem. The DRM authentication cookie is obsolete and is no longer used. If you are still getting that message, then I think you must be on an old version of wld (see https://github.com/michaelforney/wld/commit/3fe15e769cf81784215c003b18438184083af8ce). But the old version should still fall back to shm, which appears to be working for you (since it starts and st and dmenu work).

> I am on a thinkpad w540, so it is booth using an Nvidia quadro k2100M and intel i7-4800MQ iGPU, maybe thats the problem?

The nvidia GPU should work with software rendering, and the intel one with software or hardware.

**Comment by jacksmithinsulander** [comment]
Ahh so firefox wont work at all on velox?

**Comment by michaelforney** [comment]
Not in native wayland mode. It should work with xwayland.
